version: 2.1

jobs:
  build-and-test:
        docker:
            - image: cimg/node:12.16
        parallelism: 2
        steps:
            - checkout
            - restore_cache:
                name: Restore Yarn Package Cache
                keys:
                  - v1-yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: yarn install --immutable
            # change the versions from v1 to v3 to access the different caches and or incremenet to start from scratch
            - save_cache:
                name: Save Yarn Package Cache
                key: v1-yarn-packages-{{ checksum "yarn.lock" }}
                paths:
                  - ~/.cache/yarn   
            - run: mkdir ~/unitTesting
            - run:
                name: Test application
                command: |
                    TEST=$(circleci tests glob **/__tests__/*.js | circleci tests split --split-by=timings)
                    yarn test $TEST
            - run:
                command: cp junit.xml ~/unitTesting/
                when: always
            - store_test_results:
                path: ~/unitTesting
            - store_artifacts:
                path: ~/unitTesting

workflows:
  test:
    jobs:
      - build-and-test
